#!/bin/sh

fsck_enabled() {
    # We would like the output of stdout/stderr in kernel messages to
    # read them from userspace for debugging purposes. This makes the
    # debug shell in initramfs a bit awkward to work with. But is the
    # simplest way to grab output of all commands running in initramfs
    # in a place where userspace can read them afterwards
    exec >/dev/kmsg 2>&1

    # On flasher we don't run fsck
    if [ -h /dev/disk/by-label/flash-boot ]; then
        echo "[INFO] Flasher detected. We don't run fsck on the partitions when provisioning."
        return 1
    fi

    cat > "/etc/e2fsck.conf" <<EOF
[options]
broken_system_clock=1
EOF

    return 0
}

fsck_run() {
    # fsck uses mtab to see if a device is mounted
    if [ ! -e "/etc/mtab" ]; then
        ln -sf /proc/mounts /etc/mtab
    fi
    fsck.vfat -a -w /dev/disk/by-label/resin-boot
    fsck.ext4 -p /dev/disk/by-label/resin-rootA
    fsck.ext4 -p /dev/disk/by-label/resin-rootB
    fsck.ext4 -p /dev/disk/by-label/resin-state
}
